function [READINGS] = circShiftAll(READINGS)

%Mueve todas las lecturas un espacio
READINGS.COILSIGMAS=circshift(READINGS.COILSIGMAS,1);
READINGS.CABECERA=circshift(READINGS.CABECERA,1);
READINGS.MOTORS=circshift(READINGS.MOTORS,1);
READINGS.BOBINA=circshift(READINGS.BOBINA,1);
READINGS.BANDS_BOBINA=circshift(READINGS.BANDS_BOBINA,1);
READINGS.NAVIGATION=circshift(READINGS.NAVIGATION,1);
READINGS.RSSI=circshift(READINGS.RSSI,1);

end

