function [READINGS] = circShiftAll(READINGS,N_1Son,N_2Son)

%Mueve todas las lecturas un espacio
READINGS.CABECERA=circshift(READINGS.CABECERA,1);
READINGS.MOTORS=circshift(READINGS.MOTORS,1);
READINGS.NAVIGATION=circshift(READINGS.NAVIGATION,1);
READINGS.BOBINA=circshift(READINGS.BOBINA,1);
READINGS.RSSI_1Son=circshift(READINGS.RSSI_1Son,N_1Son);
READINGS.RSSI_2Son=circshift(READINGS.RSSI_2Son,N_2Son);
READINGS.THRESHOLD=circshift(READINGS.THRESHOLD,1);
READINGS.STAT_RSSI=circshift(READINGS.STAT_RSSI,1);
end

